# Generated by Django 5.1.6 on 2025-02-27 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0002_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_order',
            field=models.ForeignKey(blank=True, help_text='Related order if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_related_order', to='trading.order'),
        ),
    ]
