# Generated by Django 5.1.6 on 2025-02-27 20:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_executed', 'Order Executed'), ('order_cancelled', 'Order Cancelled'), ('order_expired', 'Order Expired'), ('order_rejected', 'Order Rejected'), ('order_approved', 'Order Approved'), ('price_alert', 'Price Alert')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('filled_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveIntegerField(default=0)),
                ('time_in_force', models.CharField(choices=[('day', 'Day Order'), ('gtc', 'Good Till Cancelled'), ('gtd', 'Good Till Date')], default='day', max_length=3)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('best_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('best_ask', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bid_quantity', models.PositiveIntegerField(default=0)),
                ('total_ask_quantity', models.PositiveIntegerField(default=0)),
                ('bid_levels', models.JSONField(default=dict)),
                ('ask_levels', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Price histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('executed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
